//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRERP_RestAPI.MelatWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interfaces.core.sw.bps.com/", ConfigurationName="MelatWebService.IPaymentGateway")]
    public interface IPaymentGateway {
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        IRERP_RestAPI.MelatWebService.bpVerifyRequestResponse bpVerifyRequest(IRERP_RestAPI.MelatWebService.bpVerifyRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        IRERP_RestAPI.MelatWebService.bpRefundInquiryRequestResponse bpRefundInquiryRequest(IRERP_RestAPI.MelatWebService.bpRefundInquiryRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        IRERP_RestAPI.MelatWebService.bpRefundVerifyRequestResponse bpRefundVerifyRequest(IRERP_RestAPI.MelatWebService.bpRefundVerifyRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        IRERP_RestAPI.MelatWebService.bpSettleRequestResponse bpSettleRequest(IRERP_RestAPI.MelatWebService.bpSettleRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        IRERP_RestAPI.MelatWebService.bpDynamicPayRequestResponse bpDynamicPayRequest(IRERP_RestAPI.MelatWebService.bpDynamicPayRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        IRERP_RestAPI.MelatWebService.bpReversalRequestResponse bpReversalRequest(IRERP_RestAPI.MelatWebService.bpReversalRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        IRERP_RestAPI.MelatWebService.bpCumulativeDynamicPayRequestResponse bpCumulativeDynamicPayRequest(IRERP_RestAPI.MelatWebService.bpCumulativeDynamicPayRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        IRERP_RestAPI.MelatWebService.bpPayRequestResponse bpPayRequest(IRERP_RestAPI.MelatWebService.bpPayRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        IRERP_RestAPI.MelatWebService.bpSaleReferenceIdRequestResponse bpSaleReferenceIdRequest(IRERP_RestAPI.MelatWebService.bpSaleReferenceIdRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        IRERP_RestAPI.MelatWebService.bpInquiryRequestResponse bpInquiryRequest(IRERP_RestAPI.MelatWebService.bpInquiryRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        IRERP_RestAPI.MelatWebService.bpRefundRequestResponse bpRefundRequest(IRERP_RestAPI.MelatWebService.bpRefundRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpVerifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpVerifyRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpVerifyRequestBody Body;
        
        public bpVerifyRequest() {
        }
        
        public bpVerifyRequest(IRERP_RestAPI.MelatWebService.bpVerifyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpVerifyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpVerifyRequestBody() {
        }
        
        public bpVerifyRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpVerifyRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpVerifyRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpVerifyRequestResponseBody Body;
        
        public bpVerifyRequestResponse() {
        }
        
        public bpVerifyRequestResponse(IRERP_RestAPI.MelatWebService.bpVerifyRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpVerifyRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpVerifyRequestResponseBody() {
        }
        
        public bpVerifyRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundInquiryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundInquiryRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpRefundInquiryRequestBody Body;
        
        public bpRefundInquiryRequest() {
        }
        
        public bpRefundInquiryRequest(IRERP_RestAPI.MelatWebService.bpRefundInquiryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundInquiryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long refundOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long refundReferenceId;
        
        public bpRefundInquiryRequestBody() {
        }
        
        public bpRefundInquiryRequestBody(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.refundOrderId = refundOrderId;
            this.refundReferenceId = refundReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundInquiryRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundInquiryRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpRefundInquiryRequestResponseBody Body;
        
        public bpRefundInquiryRequestResponse() {
        }
        
        public bpRefundInquiryRequestResponse(IRERP_RestAPI.MelatWebService.bpRefundInquiryRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundInquiryRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpRefundInquiryRequestResponseBody() {
        }
        
        public bpRefundInquiryRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundVerifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundVerifyRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpRefundVerifyRequestBody Body;
        
        public bpRefundVerifyRequest() {
        }
        
        public bpRefundVerifyRequest(IRERP_RestAPI.MelatWebService.bpRefundVerifyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundVerifyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long refundOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long refundReferenceId;
        
        public bpRefundVerifyRequestBody() {
        }
        
        public bpRefundVerifyRequestBody(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.refundOrderId = refundOrderId;
            this.refundReferenceId = refundReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundVerifyRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundVerifyRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpRefundVerifyRequestResponseBody Body;
        
        public bpRefundVerifyRequestResponse() {
        }
        
        public bpRefundVerifyRequestResponse(IRERP_RestAPI.MelatWebService.bpRefundVerifyRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundVerifyRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpRefundVerifyRequestResponseBody() {
        }
        
        public bpRefundVerifyRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpSettleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSettleRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpSettleRequestBody Body;
        
        public bpSettleRequest() {
        }
        
        public bpSettleRequest(IRERP_RestAPI.MelatWebService.bpSettleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpSettleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpSettleRequestBody() {
        }
        
        public bpSettleRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpSettleRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSettleRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpSettleRequestResponseBody Body;
        
        public bpSettleRequestResponse() {
        }
        
        public bpSettleRequestResponse(IRERP_RestAPI.MelatWebService.bpSettleRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpSettleRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpSettleRequestResponseBody() {
        }
        
        public bpSettleRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpDynamicPayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpDynamicPayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpDynamicPayRequestBody Body;
        
        public bpDynamicPayRequest() {
        }
        
        public bpDynamicPayRequest(IRERP_RestAPI.MelatWebService.bpDynamicPayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpDynamicPayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public long payerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public long subServiceId;
        
        public bpDynamicPayRequestBody() {
        }
        
        public bpDynamicPayRequestBody(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId, long subServiceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
            this.payerId = payerId;
            this.subServiceId = subServiceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpDynamicPayRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpDynamicPayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpDynamicPayRequestResponseBody Body;
        
        public bpDynamicPayRequestResponse() {
        }
        
        public bpDynamicPayRequestResponse(IRERP_RestAPI.MelatWebService.bpDynamicPayRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpDynamicPayRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpDynamicPayRequestResponseBody() {
        }
        
        public bpDynamicPayRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpReversalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpReversalRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpReversalRequestBody Body;
        
        public bpReversalRequest() {
        }
        
        public bpReversalRequest(IRERP_RestAPI.MelatWebService.bpReversalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpReversalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpReversalRequestBody() {
        }
        
        public bpReversalRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpReversalRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpReversalRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpReversalRequestResponseBody Body;
        
        public bpReversalRequestResponse() {
        }
        
        public bpReversalRequestResponse(IRERP_RestAPI.MelatWebService.bpReversalRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpReversalRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpReversalRequestResponseBody() {
        }
        
        public bpReversalRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpCumulativeDynamicPayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpCumulativeDynamicPayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpCumulativeDynamicPayRequestBody Body;
        
        public bpCumulativeDynamicPayRequest() {
        }
        
        public bpCumulativeDynamicPayRequest(IRERP_RestAPI.MelatWebService.bpCumulativeDynamicPayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpCumulativeDynamicPayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        public bpCumulativeDynamicPayRequestBody() {
        }
        
        public bpCumulativeDynamicPayRequestBody(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpCumulativeDynamicPayRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpCumulativeDynamicPayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpCumulativeDynamicPayRequestResponseBody Body;
        
        public bpCumulativeDynamicPayRequestResponse() {
        }
        
        public bpCumulativeDynamicPayRequestResponse(IRERP_RestAPI.MelatWebService.bpCumulativeDynamicPayRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpCumulativeDynamicPayRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpCumulativeDynamicPayRequestResponseBody() {
        }
        
        public bpCumulativeDynamicPayRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpPayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpPayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpPayRequestBody Body;
        
        public bpPayRequest() {
        }
        
        public bpPayRequest(IRERP_RestAPI.MelatWebService.bpPayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpPayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public long payerId;
        
        public bpPayRequestBody() {
        }
        
        public bpPayRequestBody(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
            this.payerId = payerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpPayRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpPayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpPayRequestResponseBody Body;
        
        public bpPayRequestResponse() {
        }
        
        public bpPayRequestResponse(IRERP_RestAPI.MelatWebService.bpPayRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpPayRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpPayRequestResponseBody() {
        }
        
        public bpPayRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpSaleReferenceIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSaleReferenceIdRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpSaleReferenceIdRequestBody Body;
        
        public bpSaleReferenceIdRequest() {
        }
        
        public bpSaleReferenceIdRequest(IRERP_RestAPI.MelatWebService.bpSaleReferenceIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpSaleReferenceIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        public bpSaleReferenceIdRequestBody() {
        }
        
        public bpSaleReferenceIdRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpSaleReferenceIdRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSaleReferenceIdRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpSaleReferenceIdRequestResponseBody Body;
        
        public bpSaleReferenceIdRequestResponse() {
        }
        
        public bpSaleReferenceIdRequestResponse(IRERP_RestAPI.MelatWebService.bpSaleReferenceIdRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpSaleReferenceIdRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpSaleReferenceIdRequestResponseBody() {
        }
        
        public bpSaleReferenceIdRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpInquiryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpInquiryRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpInquiryRequestBody Body;
        
        public bpInquiryRequest() {
        }
        
        public bpInquiryRequest(IRERP_RestAPI.MelatWebService.bpInquiryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpInquiryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpInquiryRequestBody() {
        }
        
        public bpInquiryRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpInquiryRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpInquiryRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpInquiryRequestResponseBody Body;
        
        public bpInquiryRequestResponse() {
        }
        
        public bpInquiryRequestResponse(IRERP_RestAPI.MelatWebService.bpInquiryRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpInquiryRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpInquiryRequestResponseBody() {
        }
        
        public bpInquiryRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpRefundRequestBody Body;
        
        public bpRefundRequest() {
        }
        
        public bpRefundRequest(IRERP_RestAPI.MelatWebService.bpRefundRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public long refundAmount;
        
        public bpRefundRequestBody() {
        }
        
        public bpRefundRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId, long refundAmount) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
            this.refundAmount = refundAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public IRERP_RestAPI.MelatWebService.bpRefundRequestResponseBody Body;
        
        public bpRefundRequestResponse() {
        }
        
        public bpRefundRequestResponse(IRERP_RestAPI.MelatWebService.bpRefundRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpRefundRequestResponseBody() {
        }
        
        public bpRefundRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentGatewayChannel : IRERP_RestAPI.MelatWebService.IPaymentGateway, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentGatewayClient : System.ServiceModel.ClientBase<IRERP_RestAPI.MelatWebService.IPaymentGateway>, IRERP_RestAPI.MelatWebService.IPaymentGateway {
        
        public PaymentGatewayClient() {
        }
        
        public PaymentGatewayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentGatewayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentGatewayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentGatewayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRERP_RestAPI.MelatWebService.bpVerifyRequestResponse IRERP_RestAPI.MelatWebService.IPaymentGateway.bpVerifyRequest(IRERP_RestAPI.MelatWebService.bpVerifyRequest request) {
            return base.Channel.bpVerifyRequest(request);
        }
        
        public string bpVerifyRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            IRERP_RestAPI.MelatWebService.bpVerifyRequest inValue = new IRERP_RestAPI.MelatWebService.bpVerifyRequest();
            inValue.Body = new IRERP_RestAPI.MelatWebService.bpVerifyRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            IRERP_RestAPI.MelatWebService.bpVerifyRequestResponse retVal = ((IRERP_RestAPI.MelatWebService.IPaymentGateway)(this)).bpVerifyRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRERP_RestAPI.MelatWebService.bpRefundInquiryRequestResponse IRERP_RestAPI.MelatWebService.IPaymentGateway.bpRefundInquiryRequest(IRERP_RestAPI.MelatWebService.bpRefundInquiryRequest request) {
            return base.Channel.bpRefundInquiryRequest(request);
        }
        
        public string bpRefundInquiryRequest(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            IRERP_RestAPI.MelatWebService.bpRefundInquiryRequest inValue = new IRERP_RestAPI.MelatWebService.bpRefundInquiryRequest();
            inValue.Body = new IRERP_RestAPI.MelatWebService.bpRefundInquiryRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.refundOrderId = refundOrderId;
            inValue.Body.refundReferenceId = refundReferenceId;
            IRERP_RestAPI.MelatWebService.bpRefundInquiryRequestResponse retVal = ((IRERP_RestAPI.MelatWebService.IPaymentGateway)(this)).bpRefundInquiryRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRERP_RestAPI.MelatWebService.bpRefundVerifyRequestResponse IRERP_RestAPI.MelatWebService.IPaymentGateway.bpRefundVerifyRequest(IRERP_RestAPI.MelatWebService.bpRefundVerifyRequest request) {
            return base.Channel.bpRefundVerifyRequest(request);
        }
        
        public string bpRefundVerifyRequest(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            IRERP_RestAPI.MelatWebService.bpRefundVerifyRequest inValue = new IRERP_RestAPI.MelatWebService.bpRefundVerifyRequest();
            inValue.Body = new IRERP_RestAPI.MelatWebService.bpRefundVerifyRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.refundOrderId = refundOrderId;
            inValue.Body.refundReferenceId = refundReferenceId;
            IRERP_RestAPI.MelatWebService.bpRefundVerifyRequestResponse retVal = ((IRERP_RestAPI.MelatWebService.IPaymentGateway)(this)).bpRefundVerifyRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRERP_RestAPI.MelatWebService.bpSettleRequestResponse IRERP_RestAPI.MelatWebService.IPaymentGateway.bpSettleRequest(IRERP_RestAPI.MelatWebService.bpSettleRequest request) {
            return base.Channel.bpSettleRequest(request);
        }
        
        public string bpSettleRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            IRERP_RestAPI.MelatWebService.bpSettleRequest inValue = new IRERP_RestAPI.MelatWebService.bpSettleRequest();
            inValue.Body = new IRERP_RestAPI.MelatWebService.bpSettleRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            IRERP_RestAPI.MelatWebService.bpSettleRequestResponse retVal = ((IRERP_RestAPI.MelatWebService.IPaymentGateway)(this)).bpSettleRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRERP_RestAPI.MelatWebService.bpDynamicPayRequestResponse IRERP_RestAPI.MelatWebService.IPaymentGateway.bpDynamicPayRequest(IRERP_RestAPI.MelatWebService.bpDynamicPayRequest request) {
            return base.Channel.bpDynamicPayRequest(request);
        }
        
        public string bpDynamicPayRequest(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId, long subServiceId) {
            IRERP_RestAPI.MelatWebService.bpDynamicPayRequest inValue = new IRERP_RestAPI.MelatWebService.bpDynamicPayRequest();
            inValue.Body = new IRERP_RestAPI.MelatWebService.bpDynamicPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            inValue.Body.subServiceId = subServiceId;
            IRERP_RestAPI.MelatWebService.bpDynamicPayRequestResponse retVal = ((IRERP_RestAPI.MelatWebService.IPaymentGateway)(this)).bpDynamicPayRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRERP_RestAPI.MelatWebService.bpReversalRequestResponse IRERP_RestAPI.MelatWebService.IPaymentGateway.bpReversalRequest(IRERP_RestAPI.MelatWebService.bpReversalRequest request) {
            return base.Channel.bpReversalRequest(request);
        }
        
        public string bpReversalRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            IRERP_RestAPI.MelatWebService.bpReversalRequest inValue = new IRERP_RestAPI.MelatWebService.bpReversalRequest();
            inValue.Body = new IRERP_RestAPI.MelatWebService.bpReversalRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            IRERP_RestAPI.MelatWebService.bpReversalRequestResponse retVal = ((IRERP_RestAPI.MelatWebService.IPaymentGateway)(this)).bpReversalRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRERP_RestAPI.MelatWebService.bpCumulativeDynamicPayRequestResponse IRERP_RestAPI.MelatWebService.IPaymentGateway.bpCumulativeDynamicPayRequest(IRERP_RestAPI.MelatWebService.bpCumulativeDynamicPayRequest request) {
            return base.Channel.bpCumulativeDynamicPayRequest(request);
        }
        
        public string bpCumulativeDynamicPayRequest(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl) {
            IRERP_RestAPI.MelatWebService.bpCumulativeDynamicPayRequest inValue = new IRERP_RestAPI.MelatWebService.bpCumulativeDynamicPayRequest();
            inValue.Body = new IRERP_RestAPI.MelatWebService.bpCumulativeDynamicPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            IRERP_RestAPI.MelatWebService.bpCumulativeDynamicPayRequestResponse retVal = ((IRERP_RestAPI.MelatWebService.IPaymentGateway)(this)).bpCumulativeDynamicPayRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRERP_RestAPI.MelatWebService.bpPayRequestResponse IRERP_RestAPI.MelatWebService.IPaymentGateway.bpPayRequest(IRERP_RestAPI.MelatWebService.bpPayRequest request) {
            return base.Channel.bpPayRequest(request);
        }
        
        public string bpPayRequest(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            IRERP_RestAPI.MelatWebService.bpPayRequest inValue = new IRERP_RestAPI.MelatWebService.bpPayRequest();
            inValue.Body = new IRERP_RestAPI.MelatWebService.bpPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            IRERP_RestAPI.MelatWebService.bpPayRequestResponse retVal = ((IRERP_RestAPI.MelatWebService.IPaymentGateway)(this)).bpPayRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRERP_RestAPI.MelatWebService.bpSaleReferenceIdRequestResponse IRERP_RestAPI.MelatWebService.IPaymentGateway.bpSaleReferenceIdRequest(IRERP_RestAPI.MelatWebService.bpSaleReferenceIdRequest request) {
            return base.Channel.bpSaleReferenceIdRequest(request);
        }
        
        public string bpSaleReferenceIdRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId) {
            IRERP_RestAPI.MelatWebService.bpSaleReferenceIdRequest inValue = new IRERP_RestAPI.MelatWebService.bpSaleReferenceIdRequest();
            inValue.Body = new IRERP_RestAPI.MelatWebService.bpSaleReferenceIdRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            IRERP_RestAPI.MelatWebService.bpSaleReferenceIdRequestResponse retVal = ((IRERP_RestAPI.MelatWebService.IPaymentGateway)(this)).bpSaleReferenceIdRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRERP_RestAPI.MelatWebService.bpInquiryRequestResponse IRERP_RestAPI.MelatWebService.IPaymentGateway.bpInquiryRequest(IRERP_RestAPI.MelatWebService.bpInquiryRequest request) {
            return base.Channel.bpInquiryRequest(request);
        }
        
        public string bpInquiryRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            IRERP_RestAPI.MelatWebService.bpInquiryRequest inValue = new IRERP_RestAPI.MelatWebService.bpInquiryRequest();
            inValue.Body = new IRERP_RestAPI.MelatWebService.bpInquiryRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            IRERP_RestAPI.MelatWebService.bpInquiryRequestResponse retVal = ((IRERP_RestAPI.MelatWebService.IPaymentGateway)(this)).bpInquiryRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRERP_RestAPI.MelatWebService.bpRefundRequestResponse IRERP_RestAPI.MelatWebService.IPaymentGateway.bpRefundRequest(IRERP_RestAPI.MelatWebService.bpRefundRequest request) {
            return base.Channel.bpRefundRequest(request);
        }
        
        public string bpRefundRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId, long refundAmount) {
            IRERP_RestAPI.MelatWebService.bpRefundRequest inValue = new IRERP_RestAPI.MelatWebService.bpRefundRequest();
            inValue.Body = new IRERP_RestAPI.MelatWebService.bpRefundRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            inValue.Body.refundAmount = refundAmount;
            IRERP_RestAPI.MelatWebService.bpRefundRequestResponse retVal = ((IRERP_RestAPI.MelatWebService.IPaymentGateway)(this)).bpRefundRequest(inValue);
            return retVal.Body.@return;
        }
    }
}
